version: '3'

services:
  publisher1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["mix", "server"]
    environment:
      - GCP_PROJECT_ID=my-awesome-project
      - PUBSUB_HOST=http://pubsub:8085
      - PUBSUB_TOPIC=my-awesome-topic
      - PUBSUB_ROLE=publisher
      - NAME=p1
      - INTERVAL=1000
    volumes:
      - ".:/app"
    depends_on:
      - pubsub
  publisher2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["mix", "server"]
    environment:
      - GCP_PROJECT_ID=my-awesome-project
      - PUBSUB_HOST=http://pubsub:8085
      - PUBSUB_TOPIC=my-awesome-topic
      - PUBSUB_ROLE=publisher
      - NAME=p2
      - INTERVAL=3000
    volumes:
      - ".:/app"
    depends_on:
      - pubsub
  subscriber1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["mix", "server"]
    environment:
      - GCP_PROJECT_ID=my-awesome-project
      - PUBSUB_HOST=http://pubsub:8085
      - PUBSUB_TOPIC=my-awesome-topic
      - PUBSUB_ROLE=subscriber
      - NAME=my-awesome-subscription1
      - INTERVAL=500
    volumes:
      - ".:/app"
    depends_on:
      - pubsub
  subscriber2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["mix", "server"]
    environment:
      - GCP_PROJECT_ID=my-awesome-project
      - PUBSUB_HOST=http://pubsub:8085
      - PUBSUB_TOPIC=my-awesome-topic
      - PUBSUB_ROLE=subscriber
      - NAME=my-awesome-subscription1
      - INTERVAL=500
    volumes:
      - ".:/app"
    depends_on:
      - pubsub
  subscriber3:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["mix", "server"]
    environment:
      - GCP_PROJECT_ID=my-awesome-project
      - PUBSUB_HOST=http://pubsub:8085
      - PUBSUB_TOPIC=my-awesome-topic
      - PUBSUB_ROLE=subscriber
      - NAME=my-awesome-subscription2
      - INTERVAL=500
    volumes:
      - ".:/app"
    depends_on:
      - pubsub
  pubsub:
    build:
      context: .
      dockerfile: Dockerfile.pubsub
    ports:
      - "8085:8085"
    volumes:
      - "./volumes/pubsub:/var/pubsub"
