version: '3'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PUBSUB_HOST=http://pubsub:8085
      - GCP_PROJECT_ID=my-awesome-project
    volumes:
      - ".:/app"
    depends_on:
      - pubsub
  pubsub:
    build:
      context: .
      dockerfile: Dockerfile.pubsub
    ports:
      - "8085:8085"
    volumes:
      - "./volumes/pubsub:/var/pubsub"
