version: '3'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
    depends_on:
      - pubsub
  pubsub:
    build:
      context: .
      dockerfile: Dockerfile.pubsub
    ports:
      - "8085:8085"
    volumes:
      - "./volumes/pubsub:/var/pubsub"
