FROM elixir:1.7

ENV DEBIAN_FRONTEND=noninteractive

RUN mix local.hex --force mix local.rebar --force

RUN apt-get update && apt-get install -y \
    inotify-tools \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
